---
title: "BanuBoopalanTidyversePart1"
author: "Banu Boopalan"
date: "12/7/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytext)
library(tidyr)
library(dplyr)
library(stringr)
library(tidytext)
library(wordcloud)
library(broom)
library(quanteda)
library(ggplot2)
library(igraph)
library(ggraph)
library(tm)
library(textdata)
#install.packages("textdata")

```

## Show Tidyverse, text sentiment analysis by taking in dataset, clean up tokens, perform igraph and bing sentiment analysis


```{r cars}
mydata <- read.csv("https://raw.githubusercontent.com/BanuB/DATA607FALL2019REPO/master/gop_debate_all1.csv", stringsAsFactors = FALSE)
names(mydata) <- c ("textcol")
#mydata[1:59,]

mydata$textcol[1:10]
str(mydata)



```

## Including Plots

```{r }
new_data <- data.frame(mydata$textcol[1:10000])
names(new_data) <- c ("textcol")
snippet_bigrams <-  new_data %>%
  unnest_tokens(bigram, textcol, token = "ngrams", n = 2)
nrow(snippet_bigrams)

snippet_bigrams %>%
  count(bigram, sort = TRUE)

bigrams_separated <- snippet_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigram_counts

# filter for only relatively common combinations
bigram_graph <- bigram_counts %>%
  filter(n > 25) %>%
  graph_from_data_frame()

bigram_graph

set.seed(2017)

ggraph(bigram_graph, layout = "kk") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```

```{r }

str(new_data)
token_dtm <- new_data %>%
  unnest_tokens(word, textcol, token = "ngrams", n = 1)

str(token_dtm)
   
unigram_filtered2 <- token_dtm %>%
  filter(!word %in% stop_words$word) 
  
   str(unigram_filtered2)
head(unigram_filtered2)

#unigram_filtered2 %>% count(word,sort = TRUE)

unigram_filtered2 %>%
  inner_join(get_sentiments("bing"), by = c(word = "word") ) %>%
  count(sentiment, word) %>%
  filter(n >= 30) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ylab("Contribution to sentiment") + ggtitle("Bing Lexicon Sentiment Analysis for corpus")


```

